import days.Day25

fun main(args: Array<String>) {
//    val day1 = Pair(runDay1("1"), runDay1("2"))
//    val day2 = Pair(runDay2("1"), runDay2("2"))
//    val day3 = Day3()
//    val day4 = Day4()
//    val day5 = Day5()
//    val day6 = Day6()
//    val day7 = Day7()
//    val day8 = Day8()
//    val day9 = Day9()
//    println(Day10().run("test"))
//    println(Day10().run("1"))
//    println(Day10().run("2"))
//    println(Day11().run("test"))
//    println(Day11().run("1"))
//    println(Day11().run("2"))
//    println(Day12().run("test"))
//    println(Day12().run("1"))
//    println(Day12().run("2"))
//    println(Day14().run("test"))
//    println(Day14().run("1"))
//    println(Day14().run("2"))
//    println(Day15().run("test"))
//    println(Day15().run("1"))
//    println(Day15().run("2"))
//    println(Day16().run("test"))
//    println(Day16().run("1"))
//    println(Day16().run("2"))
//    println(Day17().run("test"))
//    println(Day17().run("1"))
//    println(Day17().run("2"))
//    println(Day18().run("test"))
//    println(Day18().run("1"))
//    println(Day18().run("2"))
//    println(Day19().run("test"))
//    println(Day19().run("1"))
//    println(Day19().run("2"))
//    println(Day20().run("test"))
//    println(Day20().run("1"))
//    println(Day20().run("2"))
//    println(Day21().run("test"))
//    println(Day21().run("1"))
//    println(Day21().run("2"))
//    println(Day22().run("test"))
//    println(Day22().run("1"))
//    println(Day22().run("2"))
//    println(Day23().run("test"))
//    println(Day23().run("1"))
//    println(Day23().run("2"))
//    println(Day24().run("test"))
//    println(Day24().run("1"))
//    println(Day24().run("2"))
    println(Day25().run("test"))
    println(Day25().run("1"))
//    println(Day25().run("2"))

}